### ISSUE TITLE
gulp install keeps crashing

### ISSUE THREAD

**Issue by idleberg** [Semantic-Org/Semantic-UI#1568]
Whenever I use Express setup, `gulp install` keeps crashing for me. It works just fine when I choose Express and everything is checked.

````
[?] It looks like you have a semantic.json file already. Yes, extend my current settings.
[?] Set-up Semantic UI: Express (Set components and output folder)
[?] What components should we include in the package? reset, site, button, icon, image, input, label, form, grid, menu, item, dimmer, dropdown, modal, popup, search, shape, sidebar, transition, form, state, visibility
[?] Where should we output Semantic UI? dist/
Installing
------------------------------
Creating site theme folder ./src/site
fs.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy

Error: ENOENT, no such file or directory './src/_site'
    at Error (native)
    at Object.fs.statSync (fs.js:721:18)
    at Object.exports.copyDirSyncRecursive (/Users/jan/Semantic-UI/node_modules/wrench/lib/wrench.js:244:23)
    at /Users/jan/Semantic-UI/gulpfile.js:528:14
    at /Users/jan/Semantic-UI/node_modules/gulp-prompt/index.js:19:5
    at Object.<anonymous> (/Users/jan/Semantic-UI/node_modules/gulp-prompt/node_modules/inquirer/lib/inquirer.js:81:7)
    at /Users/jan/Semantic-UI/node_modules/gulp-prompt/node_modules/inquirer/node_modules/async/lib/async.js:232:13
    at /Users/jan/Semantic-UI/node_modules/gulp-prompt/node_modules/inquirer/node_modules/async/lib/async.js:142:25
    at /Users/jan/Semantic-UI/node_modules/gulp-prompt/node_modules/inquirer/node_modules/async/lib/async.js:229:17
    at Object.<anonymous> (/Users/jan/Semantic-UI/node_modules/gulp-prompt/node_modules/inquirer/lib/inquirer.js:89:7)
```

In the meantime I was thinking about building custom CSS and JS myself, will concatenating the required LESS files be enough or is there something else to keep in mind?

**Comment by jlukic** [comment]
You can use any custom set-up to parse the LESS files, just make sure you only parse ``src/definitions/``. 

Also keep in mind you cant ``@import`` definitions into other less files.
