### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by loranger** [Semantic-Org/Semantic-UI#1815]
Hello,

I tried but faild to build samentic-ui. It seems gulp-concat-css is missing a paramater.

My build settings are standard (dist/ folder) but here is the output I get :

```bash
$ gulp build
(...)
[gulp] Created: dist/components/grid.css
[gulp] Created: dist/components/menu.min.css
[gulp] Created: dist/components/menu.css
[gulp] Created: dist/components/message.css
[gulp] Created: dist/components/message.min.css
[gulp] Created: dist/components/table.css
[17:43:22] Starting 'package uncompressed css'...
[gulp] Created: dist/components/table.min.css
[17:43:22] Finished 'build' after 14 s
[17:43:22] Starting 'package compressed css'...
/path/to/semantic-ui/node_modules/gulp-concat-css/index.js:112
      base: firstFile.base,
                     ^
TypeError: Cannot read property 'base' of undefined
    at DestroyableTransform._flush (/path/to/semantic-ui/node_modules/gulp-concat-css/index.js:112:22)
    at DestroyableTransform.<anonymous> (/path/to/semantic-ui/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
    at prefinish (/path/to/semantic-ui/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:450:12)
    at finishMaybe (/path/to/semantic-ui/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:458:7)
    at endWritable (/path/to/semantic-ui/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at DestroyableTransform.Writable.end (/path/to/semantic-ui/node_modules/gulp-concat-css/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at Stream.onend (stream.js:79:10)
    at Stream.emit (events.js:129:20)
```

Did I miss something ?

I did checkout semantic-ui/1.0 on a OSX 10.10.2
I use npm 2.5.1 and gulp 3.8.11.

**Comment by loranger** [comment]
Interesting :
The issue happens when I build Semantic UI using express install.
Automatic install does not fail, whereas the semantic.json looks the same.

**Comment by jlukic** [comment]
I'm about to release new build tools today/tomorrow. 

Can you confirm if you have the same issues when building from that branch?

NPM
```bash
npm install semantic-org/semantic-ui#next
```

or just clone branch

**Comment by loranger** [comment]
It work flawlessly !

Can't wait for tomorrow ;)

**Comment by loranger** [comment]
I git pull the last version (1.10.4) and it seems the bug is back...
Sorry for that.
