### ISSUE TITLE
Undeclared dependency on "clone" causes npm install to fail

### ISSUE THREAD

**Issue by lox** [Semantic-Org/Semantic-UI#1871]
On installing semantic-ui, I get the following error:

```
|
> semantic-ui@1.10.2 install /Users/lachlan/.go/src/github.com/lox/xyz/node_modules/semantic-ui
> gulp install

module.js:338
    throw err;
          ^
Error: Cannot find module 'clone'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/lachlan/.go/src/github.com/lox/xyz/node_modules/gulp-util/node_modules/vinyl/index.js:2:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by jlukic** [comment]
Just tested on ubuntu with `npm install semantic-ui` and its working for me. If you have a `package.json` setup for your project try `rm`ing node_modules and re-installing, `npm update`

If you are still getting the issue, do you have any more info. Do you have other dependencies in the project? What platform?

**Comment by jlukic** [comment]
Perhaps try `npm cache clean`

**Comment by dannynimmo** [comment]
@lox Did you ever work out what was happening? I'm getting this same error.

**Comment by bionikspoon** [comment]
@dannynimmo I got this after keyboard interrupting a package installation.  `npm cache clean` and reinstalling said package did the job.

**Comment by italomaia** [comment]
I'm having this issue on ubuntu 17.04
