### ISSUE TITLE
Error: Task watchui can't support dependencies that is not an array of strings

### ISSUE THREAD

**Issue by TehCrucible** [Semantic-Org/Semantic-UI#2653]
Another issue with importing tasks from main repo into my own gulp file.  Note that I've changed my task name to `watchui` rather than `watch ui`. Throws this exception:
```
C:\Users\jamie_000\OneDrive\Crucible\Cairns Key\website\cairnskeyTheme>gulp watchui
C:\Users\jamie_000\OneDrive\Crucible\Cairns Key\website\cairnskeyTheme\node_modules\gulp\node_modules\orchestrator\index.js:47
                        throw new Error('Task '+name+' can\'t support dependencies that is not an a
                              ^
Error: Task watchui can't support dependencies that is not an array of strings
    at Gulp.Orchestrator.add (C:\Users\jamie_000\OneDrive\Crucible\Cairns Key\website\cairnskeyTheme\node_modules\gulp\node_modules\orchestrator\index.js:47:10)
    at Object.<anonymous> (C:\Users\jamie_000\OneDrive\Crucible\Cairns Key\website\cairnskeyTheme\gulpfile.js:32:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\jamie_000\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\jamie_000\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)
```
Seems to be fixed by removing the text descriptions of the tasks from the suggested code like so:
```
// import task with a custom task name
gulp.task('watch ui', watch));
gulp.task('build ui', build));
```

**Comment by jlukic** [comment]
Yeah, i've revised the examples. The second parameter is for people using [gulp help](https://www.npmjs.com/package/gulp-help)

**Comment by fholzer** [comment]
Seems like there's still an issue with this...
1. gulp-help is still required, because your commit added `gulp.task` with the gulp-help parameter to `tasks/collections/rtl.js`
2. The documentation for this needs a minor fix too.
