### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by hendricha** [Semantic-Org/Semantic-UI#3124]
Gulp install fails for me from npm install, I keep getting the following error:
```
$  npm install semantic-ui
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN excluding symbolic link tests/withsymlinks/.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests/withsymlinks/bar.txt -> ../shown/bar.txt
npm WARN optional dep failed, continuing fsevents@1.0.1
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine postcss@5.0.8: wanted: {"node":">=0.12"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.9.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
-
> semantic-ui@2.1.4 install /home/hendricha/Coding/project/node_modules/semantic-ui
> gulp install

[08:55:25] Using gulpfile ~/Coding/project/node_modules/semantic-ui/gulpfile.js
[08:55:25] Starting 'install'...

Updating Semantic UI from undefined to 2.1.4
Updating ui definitions...
Updating default theme...
Updating tasks...
[08:55:26] 'install' errored after 80 ms
[08:55:26] Error: ENOENT, no such file or directory '/home/hendricha/Coding/project/semantic/tasks/'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Object.exports.copyDirSyncRecursive (/home/hendricha/Coding/project/node_modules/semantic-ui/node_modules/wrench/lib/wrench.js:246:12)
    at Gulp.module.exports (/home/hendricha/Coding/project/node_modules/semantic-ui/tasks/install.js:119:14)
    at module.exports (/home/hendricha/Coding/project/node_modules/semantic-ui/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/hendricha/Coding/project/node_modules/semantic-ui/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/hendricha/Coding/project/node_modules/semantic-ui/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/hendricha/Coding/project/node_modules/semantic-ui/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /home/hendricha/Coding/project/node_modules/semantic-ui/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)

npm ERR! semantic-ui@2.1.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.1.4 install script.
npm ERR! This is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-30-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "semantic-ui"
npm ERR! cwd /home/hendricha/Coding/project
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by hendricha** [comment]
Cloning it from git and runing npm install in the folder produces the same error.

**Comment by jlukic** [comment]
ENOENT would be a permissions issue. NPM doesn't have permission to create a folder in your project path.

**Comment by hendricha** [comment]
Actually it had a permission issue in the .npm cache folder, I deleted it, started it again, and it worked. Thanks anyways.
