### ISSUE TITLE
no gulp file found

### ISSUE THREAD

**Issue by Maxhodges** [Semantic-Org/Semantic-UI#3222]
I setup a semantic-ui project on my notebook computer, and committed it to github. Now I'm on a new machine and when I pull the project I can't run gulp. I installed gulp as stated but i get gulp file not found.

```
maxs-imac:wreHomePage maxhodges$ gulp
[16:30:57] Local gulp not found in ~/Documents/github/wreHomePage
[16:30:57] Try running: npm install gulp
maxs-imac:wreHomePage maxhodges$ npm install gulp
gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── semver@4.3.6
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (ansi-styles@2.1.0, supports-color@2.0.0, escape-string-regexp@1.0.3, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.3, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, fancy-log@1.1.0, beeper@1.1.0, lodash._reescape@3.0.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
maxs-imac:wreHomePage maxhodges$ gulp
[16:31:12] No gulpfile found
maxs-imac:wreHomePage maxhodges$ cd semantic
maxs-imac:semantic maxhodges$ gulp
module.js:339
    throw err;
    ^

Error: Cannot find module 'gulp-help'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/maxhodges/Documents/github/wreHomePage/semantic/gulpfile.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
maxs-imac:semantic maxhodges$ 
```
repo here
https://github.com/white-rabbit-japan/wreHomePage

**Comment by Banandrew** [comment]
Hey,

I think you need to navigate to the root of your repository where `semantic.json` is located and run `npm install semantic-ui --save` there—it will update Semantic UI to the last version, so keep that in mind. Delete `node_modules` folder beforehand, though, to keep everything clean; if you're on Windows that has problems deleting it, try [rimraf package](https://www.npmjs.com/package/rimraf).

**Comment by Maxhodges** [comment]
Thanks mate!
I ended up installing semantic to a new folder, and copying over my src, img and html. I'll try your way next time!
