### ISSUE TITLE
semantic.min.css file not found

### ISSUE THREAD

**Issue by rehan-dev** [Semantic-Org/Semantic-UI#3431]
when i install semantic-ui using npm install semantic-ui --save after that i choose automatically install and then going into semantic folder and build gulp like gulp build its show some errors and then i look into the semantic/dist folder there is no semantic.min.css just semantic.js, semantic.min.js and some folder exists.

i am using windows 8.1 with proper installation of npm and gulp because i am also using foundation and bootstrap but i am not facing such types of issue since before so please solve this issue ASAP.

thanks

**Comment by jlukic** [comment]
Hi @Rehankhan100 please check out our [contributing guide](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md), it provides some suggestions on how to create a bug report so I can help determine the nature of your issues. 

I'm unable to reproduce any issues installing Semantic UI from windows using `npm install semantic-ui` perhaps you can provide more details?

**Comment by kawaiSky** [comment]
I am also facing the same issue.
when i do "gulp build", i got these errors:
```
[15:09:17] Created: dist/components/dropdown.min.js
Potentially unhandled rejection [2] TypeError: Cannot call method 'match' of undefined
    at DestroyableTransform.module.exports.settings.plumber.less.errorHandler (/home/html/semantic/tasks/config/tasks.js:92:29)
    at DestroyableTransform.emit (events.js:117:20)
    at afterTransform (/home/html/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:19)
    at TransformState.afterTransform (/home/html/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at /home/html/node_modules/gulp-less/index.js:58:14
    at tryCatchReject (/home/html/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/html/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/home/html/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/home/html/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/html/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
[15:09:17] Created: dist/components/embed.min.js
[15:09:17] Created: dist/components/modal.js
```
the version is "Semantic UI 2.1.6"

**Comment by ricardobarantini** [comment]
Having the same problem here. @kawaiSky you could solve?

**Comment by Banandrew** [comment]
Considering how many relevant issues with thorough discussions are there, I think that this one can be safely closed. If someone stumbles on it in the future, please take a look at opened issues labeled as `Build Tools`.
