### ISSUE TITLE
gulp build not building CSS

### ISSUE THREAD

**Issue by ALCC01** [Semantic-Org/Semantic-UI#3468]
First time building Semantic UI, I noticed that `gulp build` executed and exited successfully, but it did not build CSS files, so I ran another time the single task (`gulp build-css`). Not even this time the build was successful.

```
$ gulp build-css
[16:13:10] Using gulpfile --snip--/semantic/gulpfile.js
[16:13:10] Starting 'build-css'...
Building CSS
Potentially unhandled rejection [2] TypeError: Cannot call method 'match' of undefined
    at DestroyableTransform.module.exports.settings.plumber.less.errorHandler (--snip--/semantic/tasks/config/tasks.js:92:29)
    at DestroyableTransform.EventEmitter.emit (events.js:117:20)
    at afterTransform (--snip--/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:75:19)
    at TransformState.afterTransform (--snip--/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:59:12)
    at --snip--/node_modules/gulp-less/index.js:58:14
    at tryCatchReject (--snip--/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (--snip--/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (--snip--/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (--snip--/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (--snip--/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/Scheduler.js:62:19)
```

**Comment by arrowing** [comment]
I find same issue and a way to solve it: https://github.com/Semantic-Org/Semantic-UI/issues/3468

**Comment by kataras** [comment]
I have not errors on my screen but css files are not served, using npm 3.3.12 , nodejs 5.3.0, gulp 3.9.0, semantic-ui version 2.1.7.

**Comment by kevspadilla** [comment]
+1

**Comment by lucasyue** [comment]
+1

**Comment by lucasyue** [comment]
Installing gulp-autoprefixer@2.3.1 fixed it

**Comment by alvaro-canepa** [comment]
@antsav Using NVM is the best solution.
Thanks!!!!

**Comment by morenoh149** [comment]
I tried with node v4.4.7 and v5.10.0 and I still cant get the css files to build.

**Comment by aschrijver** [comment]
Not generating css, no errors displayed

Versions:
```
semantic-ui: 2.2.13
npm: 5.5.1
node: 9.3.0 (also tried with 8.4.0)
gulp CLI: 1.2.1
gulp: 3.9.1
ubuntu: 4.4.0-104-generic
```

It didn't work in my existing project, so I created a wholly clean project with semanti-ui only. Nope.
I tried the `gulp-autoprefixer` workaround, and moving the `semantic.json` to `/semantic`. Same results.
