### ISSUE TITLE
Gulp build fail

### ISSUE THREAD

**Issue by vinhtq** [Semantic-Org/Semantic-UI#3554]
I get this error when i use gulp build
```
[09:45:49] Starting 'package compressed js'...
[09:45:49] 'package compressed js' errored after 11 ms
[09:45:49] TypeError: through.obj is not a function
    at module.exports (/Volumes/DATA/Temp/demo/node_modules/gulp-header/index.js:68:18)
    at Gulp.<anonymous> (/Volumes/DATA/Temp/demo/semantic/tasks/collections/internal.js:100:15)
    at module.exports (/Volumes/DATA/Temp/demo/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Volumes/DATA/Temp/demo/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Volumes/DATA/Temp/demo/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Volumes/DATA/Temp/demo/node_modules/orchestrator/index.js:134:8)
    at Stream.<anonymous> (/Volumes/DATA/Temp/demo/semantic/tasks/build/javascript.js:71:12)
    at emitNone (events.js:67:13)
    at Stream.emit (events.js:166:7)
    at end (/Volumes/DATA/Temp/demo/node_modules/gulp-print/node_modules/map-stream/index.js:116:39)
[09:45:49] 'build' errored after 4.48 s
[09:45:49] Error in plugin 'run-sequence'
Message:
    An error occured in task 'package compressed js'.
[09:45:49] Starting 'package uncompressed js'...
[09:45:49] 'package uncompressed js' errored after 4.93 ms
[09:45:49] TypeError: through.obj is not a function
    at module.exports (/Volumes/DATA/Temp/demo/node_modules/gulp-header/index.js:68:18)
    at Gulp.<anonymous> (/Volumes/DATA/Temp/demo/semantic/tasks/collections/internal.js:86:15)
    at module.exports (/Volumes/DATA/Temp/demo/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Volumes/DATA/Temp/demo/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Volumes/DATA/Temp/demo/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Volumes/DATA/Temp/demo/node_modules/orchestrator/index.js:134:8)
    at Stream.<anonymous> (/Volumes/DATA/Temp/demo/semantic/tasks/build/javascript.js:72:12)
    at emitNone (events.js:67:13)
    at Stream.emit (events.js:166:7)
    at end (/Volumes/DATA/Temp/demo/node_modules/gulp-print/node_modules/map-stream/index.js:116:39)
[09:45:49] Finished 'build-javascript' after 4.48 s
```

Can anyone help me?

**Comment by jlukic** [comment]
Looks like its erroring at Line 100 of `internal.js` which is gulp-header (adds the comment headers).

Check you have all the dependencies, by running `npm update` again in project directory home. You can also verify manually that `gulp-header` is in `node_modules`

**Comment by vinhtq** [comment]
Thanks for your response!

I used bower to install, no error.

**Comment by orhanmaden** [comment]
I had the same issue. I resolved it by navigating to folder node_modules\gulp-header\ and running the command `run npm install`
