### ISSUE TITLE
[Build Tools] Error running setup on Windows 10

### ISSUE THREAD

**Issue by Francismori7** [Semantic-Org/Semantic-UI#4292]
```
$ npm install semantic-ui --save-dev
npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css
npm WARN excluding symbolic link tests\withsymlinks\.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests\withsymlinks\bar.txt -> ../shown/bar.txt
npm WARN excluding symbolic link tests\withsymlinks\.hidden -> ../shown/.hidden
npm WARN excluding symbolic link tests\withsymlinks\bar.txt -> ../shown/bar.txt
npm WARN prefer global js-beautify@1.5.10 should be installed with -g

> semantic-ui@2.2.2 install C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\semantic-ui
> gulp install

[17:13:23] Using gulpfile ~\Documents\PHPStorm\BabyShowers\node_modules\semantic-ui\gulpfile.js
[17:13:23] Starting 'install'...
[17:13:23] Starting 'run setup'...
? Set-up Semantic UI (Use arrow keys)
> Automatic (Use defaults locations and all components)
  Express (Set components and output folder)
  Custom (Customize all src/dist values) [17:13:23] 'run setup' errored after 52 ms
[17:13:23] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\rx-lite\rx.lite.js:63:31)
[17:13:23] 'install' errored after 59 ms
[17:13:23] SyntaxError in plugin 'run-sequence(run setup)'
Message:
    Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
Stack:
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\Francis\Documents\PHPStorm\BabyShowers\node_modules\rx-lite\rx.lite.js:63:31)
```

**Comment by Clindbergh** [comment]
Same problem on Win7. No success with v2.2.0, but [2.1.8](https://github.com/Semantic-Org/Semantic-UI/tree/2.1.8) works.
The error happens after 
> \>Automatic (Use defaults locations and all components)
    Express (Set components and output folder)
    Custom (Customize all src/dist values) 

is printed but before any user interaction (did not press `ENTER`)

**Comment by gak** [comment]
I can replicate this in Ubuntu 16.04 with this Dockerfile:

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y build-essential curl
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g gulp
RUN npm install semantic-ui@2.2.0
```

And the fix, as @Clindbergh mentioned, is to use 2.1.8 instead.

**Comment by jlukic** [comment]
I work primarily in 16.04 and havent run into this issue, but I'll try to replicate.

**Comment by XuJinNet** [comment]
The same error on win10, node.js 6:

> ? Set-up Semantic UI (Use arrow keys)
Automatic (Use defaults locations and all components)
  Express (Set components and output folder)
  Custom (Customize all src/dist values) [18:34:16] 'run setup' errored after 45 ms
[18:34:16] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at RegExp (native)
    at breakLines (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at ScreenManager.render (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (E:\My_Projects\Java\Work_Space_For_IDEA\eefung\eefung-website-nodejs\node_modules\rx-lite\rx.lite.js:63:31)
[18:34:16] 'install' errored after 51 ms
[18:34:16] SyntaxError in plugin 'run-sequence(run s

**Comment by fsbahman** [comment]
Same error, Running on windows 10, I've tried multiple version of Node from 2.X to 6.X all give me same error.

**Comment by brianveltman** [comment]
Same indeed.. Running Windows 10

**Comment by DrowningElysium** [comment]
Also on Windows 10, same error. Version 2.1.8 does allow me to install but doesn't allow me to use the arrow keys to change configuration settings. 

I am using git bash with the standard settings.

**Comment by brianveltman** [comment]
SUI 2.2.4 seems to work fine on Windows 10. Older versions are failing.

**Comment by ValeriaVG** [comment]
2.2.4 installation still fails on win10
readline.js:925
            throw err;
            ^

TypeError: Cannot read property 'name' of undefined
    at Prompt.render (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\list.js:95:69)
    at Prompt.onSubmit (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\lib\prompts\list.js:116:8)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1469:31)
    at AnonymousObserver.tryCatcher (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)
    at AutoDetachObserverPrototype.next (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:5782:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1469:31)
    at AnonymousObserver._onNext (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:4234:13)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1535:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (D:\WORK\forbo\OF\node_modules\semantic-ui\node_modules\gulp-prompt\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:1469:31)
 npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.2.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.2.4 install script 'gulp install'.
npm ERR! This is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\WORK\forbo\OF\npm-debug.log
[npm-debug.txt](https://github.com/Semantic-Org/Semantic-UI/files/453934/npm-debug.txt)

**Comment by TZK-** [comment]
Same error on Windows 8 / 2012.
Still no fix ?

**Comment by Francismori7** [comment]
hey guys! i fixed this by using bootstrap! 

thanks for the no help there.

**Comment by jkramp** [comment]
Same here when it runs setup after Is this your project folder?

Windows 10 throws

`readline.js:930
            throw err;
            ^
TypeError: Cannot read property 'name' of undefined`

**Comment by TZK-** [comment]
I've maybe found a solution. Actually I was running npm through Git Bash, so I tried to run it again with the cmd (with administrator privileges) and It worked...

**Comment by sbritoig** [comment]
I think that I've tracked this down:
- gulp-prompt@0.20 is depends on inquirer@0.10.1
- inquirer@0.10.1 depends on cli-width and 0.10.1 version don't handle correctly when cli-width returns 0 in some environments;

Inspecting the cli-width library I've noticed that it look for an environment variable named CLI_WIDTH. So the fix is just set this variable to a number greater than 1.

**Comment by mrkam** [comment]
Seems like that gulp-prompt is no longer maintained. There are many users reporting the same failure and several forks that all update to the newer inquirer

**Comment by bluesinsoul** [comment]
After several failed attempts I managed to successfully install semantic ui on windows 10. 
I'm not sure if the 2nd step helped or not but these are the adjustment I made:

1) run cmd in administrative mode;
2) set the answer to "Should we set permissions on outputted files" to no;

**Comment by mittinatten** [comment]
I had the same problem with 2.2.7 in Red Hat 7. Step 2 in the previous comment solved it for me. No need to run as admin/sudo.

**Comment by Mariyo** [comment]
I have same issue on Win 10. There are 2 ways how to run `npm install`:

1. downgrade `Semantic-Org/Semantic-UI` from current `2.2.7` to `2.1.8`
2. or run `npm install` on version `2.2.7` from `cmd` but as Administrator

**Comment by NingZaizai** [comment]
downgrad to 2.1.8 works, but any other fix?

**Comment by hitminxuanwang** [comment]
@TZK- worked for me thx

**Comment by soar** [comment]
Still have same issue in Docker and `node:latest` image:

```
> semantic-ui@2.2.10 install /usr/local/lib/node_modules/semantic-ui
> gulp install

[10:46:23] Using gulpfile /usr/local/lib/node_modules/semantic-ui/gulpfile.js
[10:46:23] Starting 'install'...
[10:46:23] Starting 'run setup'...
? Set-up Semantic UI (Use arrow keys)
❯ Automatic (Use defaults locations and all components)
  Express (Set components and output folder)
  Custom (Customize all src/dist values) [10:46:23] 'run setup' errored after 23 ms
[10:46:23] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at module.exports.ScreenManager.render (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/prompts/list.js:103:15)
    at Prompt._run (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/prompts/list.js:74:8)
    at Prompt.run (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/usr/local/lib/node_modules/semantic-ui/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/semantic-ui/node_modules/rx-lite/rx.lite.js:63:31)
[10:46:23] 'install' errored after 26 ms
[10:46:23] SyntaxError in plugin 'run-sequence(run setup)'
Message:
    Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
Stack:
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at module.exports.ScreenManager.render (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/prompts/list.js:103:15)
    at Prompt._run (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/prompts/list.js:74:8)
    at Prompt.run (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/usr/local/lib/node_modules/semantic-ui/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/semantic-ui/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/semantic-ui/node_modules/rx-lite/rx.lite.js:63:31)
```

**Comment by guaguawa** [comment]
I have the same error!!! I use git bash, but I can not solve this problem. From the error, it shows regex in inquirer.js.  I run "npm update inquirer", this error disappears but I encounter other problem. 

Then I use the cmd as an administrator. But still get regex error. I run "npm update inquirer", next "npm install semantic-ui", it works!

OS: win10 x64
git bash:  can not solve this error
cmd(admin): "npm install semantic-ui"------>"npm update inquirer"--------->"npm install semantic-ui" --------> it works

**Comment by jlukic** [comment]
I just tested on Windows 10 command prompt, and Ubuntu 16.04, and was able to install correctly without issue.

Confirmed working for me
Windows - NPM 5.0.4 and Node 6.9.1 
Ubuntu - NPM 5.0.4 and Node 7.10.0

**Comment by gotenxds** [comment]
This seems to happen to me only in git bash, using windows cmd (bahh) I get not errors.

**Comment by johot** [comment]
Also got this working from PowerShell but not git bash.
