### ISSUE TITLE
[Build Tools] install crash

### ISSUE THREAD

**Issue by ror6ax** [Semantic-Org/Semantic-UI#4374]
`npm install semantic-ui --save` gives me this:

```
[13:05:16] Starting 'install'...

[13:05:16] 'install' errored after 3.5 ms
[13:05:16] Error: Task run setup is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at /Users/user/development/blstreammap/fl/node_modules/run-sequence/index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (/Users/user/development/blstreammap/fl/node_modules/run-sequence/index.js:13:11)
    at runSequence (/Users/user/development/blstreammap/fl/node_modules/run-sequence/index.js:92:2)
    at Gulp.module.exports (/Users/user/development/blstreammap/fl/node_modules/semantic-ui/tasks/install.js:450:1)
    at module.exports (/Users/user/development/blstreammap/fl/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/user/development/blstreammap/fl/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/user/development/blstreammap/fl/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/user/development/blstreammap/fl/node_modules/orchestrator/index.js:134:8)
    at /Users/user/development/blstreammap/fl/node_modules/semantic-ui/node_modules/gulp/bin/gulp.js:129:20
npm WARN fl@0.0.0 No description
npm WARN fl@0.0.0 No repository field.
npm WARN fl@0.0.0 No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.10.0/bin/node" "/usr/local/bin/npm" "install" "semantic-ui" "--save"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.2.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.2 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/development/blstreammap/fl/npm-debug.log

```

error log as follows:

```
30818 verbose stack Error: semantic-ui@2.2.2 install: `gulp install`
30818 verbose stack Exit status 1
30818 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
30818 verbose stack     at emitTwo (events.js:100:13)
30818 verbose stack     at EventEmitter.emit (events.js:185:7)
30818 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
30818 verbose stack     at emitTwo (events.js:100:13)
30818 verbose stack     at ChildProcess.emit (events.js:185:7)
30818 verbose stack     at maybeClose (internal/child_process.js:850:16)
30818 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
30819 verbose pkgid semantic-ui@2.2.2
30820 verbose cwd /Users/user/development/blstreammap/fl
30821 error Darwin 15.6.0
30822 error argv "/usr/local/Cellar/node/5.10.0/bin/node" "/usr/local/bin/npm" "install" "semantic-ui" "--save"
30823 error node v5.10.0
30824 error npm  v3.8.3
30825 error code ELIFECYCLE
30826 error semantic-ui@2.2.2 install: `gulp install`
30826 error Exit status 1
30827 error Failed at the semantic-ui@2.2.2 install script 'gulp install'.
30827 error Make sure you have the latest version of node.js and npm installed.
30827 error If you do, this is most likely a problem with the semantic-ui package,
30827 error not with npm itself.
30827 error Tell the author that this fails on your system:
30827 error     gulp install
30827 error You can get information on how to open an issue for this project with:
30827 error     npm bugs semantic-ui
30827 error Or if that isn't available, you can get their info via:
30827 error     npm owner ls semantic-ui
30827 error There is likely additional logging output above.
30828 verbose exit [ 1, true ]
```

**Comment by jlukic** [comment]
Is gulp installed? `npm install -g gulp`

**Comment by ror6ax** [comment]
Yes it is.

**Comment by IonutBajescu** [comment]
Alright, let's try some troubleshooting. 

1. Open the file `node_modules/semantic-ui/tasks/install.js` in your preferred editor.
2. On line 26, you should see `runSequence    = require('run-sequence'),`, please replace it with `runSequence    = require('run-sequence').use(gulp),`
3. cd in node_modules/semantic-ui and manually run `gulp install`.

Let me know if it worked.

**Comment by justRu** [comment]
I had the same issue. Proposed change made it work. Thanks

**Comment by jlukic** [comment]
@IonutBajescu what's this fix exactly? Is this something i should patch in the installer?

**Comment by IonutBajescu** [comment]
@jlukic Yeah, probably. Someone might have multiple gulp versions across his project and `use(gulp)` makes sure that run-sequence uses the one you want. 

Nonetheless, I haven't been able to replicate the issue on my computer yet. Better wait until we have a few more confirmations.

@justRu Can you please run `npm -v`, `node -v` and `gulp -v` and reply here with the output you get?

**Comment by justRu** [comment]
\> npm -v
3.10.3
\> node -v
v6.3.0
\> gulp -v
[07:34:30] CLI version 3.9.1
[07:34:30] Local version 3.8.11

**Comment by fernandaparisi** [comment]
Just got the same error:

```
npm ERR! semantic-ui@2.2.4 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.2.4 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.
```

Error log is here - [npm-debug.txt](https://github.com/Semantic-Org/Semantic-UI/files/504116/npm-debug.txt)

semantic-ui dir wasn't even copied to node_modules. 
I noticed that this constantly happens if I have a semantic.json file on project root. If I run `npm install` from scratch it goes smoothly. This is the semantic.json file I've been using: [semantic.json.txt](https://github.com/Semantic-Org/Semantic-UI/files/504117/semantic.json.txt)

Running on macos 10.10.5. Gulp, NPM and node versions are:

```
☁  node -v
v6.2.0
☁  npm -v
3.10.8
☁  gulp -v
[03:01:27] CLI version 3.9.1
[03:01:27] Local version 3.9.1
```

**Comment by PixelStroke** [comment]
I received this error until I updated node, npm and gulp components to the following versions below. Afterwards the installation went through without issue.

I am running Windows 10 Enterprise (1601)
<pre>
<code>☁  node -v
v6.9.2
☁  npm -v
4.0.5
☁  gulp -v
CLI version 3.9.1
Local version 3.9.1</code>
</pre>

**Comment by almino** [comment]
On Debian it shows the same error
```
$ node -v
v0.10.29

$ npm -v
1.4.21

$ gulp -v
CLI version 3.9.1
Local version 3.9.1
```

**Comment by lisamschachtschneider** [comment]
Has this been resolved for anyone?
I'm having the same error,
`npm ERR! Failed at the semantic-ui@2.2.7 install script 'gulp install'.`
 here's my versioning:
`$ npm -v
4.0.5
$ node -v
v7.4.0
$ gulp -v
[14:09:43] CLI version 3.9.1
[14:09:43] Local version 4.0.0-alpha.2`

and semantic-ui dir wasn't copied to node_modules.
Any help would be appreciated!

**Comment by tarvos21** [comment]
Same issue here, try tens of time, but have no idea how to solve.

**Comment by vinayakkulkarni** [comment]
@tarvos21, @lisamschachtschneider: can you guys please post your gulpfile?

**Comment by almino** [comment]
I had to manually download node and reinstall it. The Debian repository is outdated. Now, it works.

**Comment by tarvos21** [comment]
@vinayakkulkarni , I just use the default gulpfile, never change anything.

**Comment by almino** [comment]
Follow these steps to solve the problem: http://askubuntu.com/a/480642/63408

**Comment by italomaia** [comment]
I'm also affected. Using node 8.1.3 and npm 5.0.3

**Comment by jlukic** [comment]
I haven't been able to repro so I'm going to unassign a milestone for now
