### ISSUE TITLE
build-docs fails out of the box

### ISSUE THREAD

**Issue by cdaringe** [Semantic-Org/Semantic-UI#4728]
# problem statement

immediately after installing semantic-ui, and using the default settings at user prompt, I did the following:

`cd semantic && gulp build-docs`, which yields

```
$ gulp build-docs
[12:44:31] Using gulpfile ~/node/octagon.react/semantic/gulpfile.js
[12:44:31] Starting 'build-docs'...
Building Metadata
Copying examples
Copying LESS source
Building Semantic for docs
(node:92547) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[12:44:31] Finished 'build-docs' after 59 ms
[12:44:31] Starting 'package compressed docs css'...
[12:44:31] Starting 'package compressed docs js'...
[12:44:31] Starting 'package uncompressed docs js'...
[12:44:31] Starting 'package uncompressed docs css'...
fs.js:89
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open '/Users/cdieringer/node/docs/out/metadata.json'
    at rethrow (fs.js:89:21)
    at maybeCallback (fs.js:107:42)
    at Object.fs.writeFile (fs.js:1284:18)
    at Stream.<anonymous> (/Users/cdieringer/node/octagon.react/semantic/tasks/docs/build.js:83:10)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at end (/Users/cdieringer/node/octagon.react/node_modules/map-stream/index.js:116:39)
    at Stream.stream.end (/Users/cdieringer/node/octagon.react/node_modules/map-stream/index.js:122:5)
    at DestroyableTransform.onend (/Users/cdieringer/node/octagon.react/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_reada
ble.js:523:10)
    at DestroyableTransform.g (events.js:291:16)
```

# discussion

- the installer dumped a `semantic.json` in my package root, vs in the `semanic/` folder.  when i go to build the docs, it tries to build docs in parent dir to my project.  this is erroneous
- when I do move my `semantic.json` to the `semantic/` folder, it fails with the above again, but this time because `<project-root>/docs/out` doesn't exist. if i manually create docs/out, the content generates
- i expected `build-docs` to build docs. instead, what i got was a bunch of SUI assets.

this was confusing to me.

what i was hoping for was a tool I could run against a config or a dir in my project that builds the SUI CSS with my customizations.  it would be great if at some point semantic can modularize some, such that I don't need to copy all of the semantic base source into my project--i can just include my modifications, run `semantic-ui build -c my-semantic-config --css-only -o ./blah.css`

**Comment by mediafreakch** [comment]
same here. Any ideas how to resolve this?

**Comment by Banandrew** [comment]
Hi, have you figured it out?

**Comment by lawrencecushman** [comment]
I am getting this error as well.

**Comment by patrick-samy** [comment]
Hi, has anyone found a workaround?

**Comment by mkennedy3000** [comment]
Follow the instructions here: https://semantic-ui.com/introduction/advanced-usage.html#download-docs-server

Essentially clone that project (call it docs) next to your semantic project (ui) and follow the rest of the instructions. Hope it helps

**Comment by jlukic** [comment]
I can't debug entirely, but the original issue seems like a permissions issue where gulp isnt allowed to write files in `../docs/out`

**Comment by abolfazl-ziaratban** [comment]
i have this same error.
`gulp build ` is working but `gulp build-docs` not working.
**output**
```
C:\Windows\system32>cd C:\xampp\htdocs\project-ui

C:\xampp\htdocs\project-ui>cd semantic

C:\xampp\htdocs\project-ui\semantic>gulp build-docs
[15:12:42] Using gulpfile C:\xampp\htdocs\project-ui\semantic\gulpfile.js
[15:12:42] Starting 'build-docs'...
Building Metadata
Copying examples
Copying LESS source
Building Semantic for docs
[15:12:42] Finished 'build-docs' after 75 ms
[15:12:42] Starting 'package compressed docs css'...
[15:12:42] Starting 'package compressed docs js'...
[15:12:42] Starting 'package uncompressed docs js'...
[15:12:42] Starting 'package uncompressed docs css'...
fs.js:101
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\docs\out\metadat
a.json'
    at Error (native)

C:\xampp\htdocs\project-ui\semantic>
```

**Comment by Iuriy-Budnikov** [comment]
+1 

```
[16:52:47] Starting 'build-docs'...
Building Metadata
Copying examples
Copying LESS source
Building Semantic for docs
(node:9111) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[16:52:47] Finished 'build-docs' after 79 ms
[16:52:47] Starting 'package compressed docs css'...
[16:52:47] Starting 'package compressed docs js'...
[16:52:47] Starting 'package uncompressed docs js'...
[16:52:47] Starting 'package uncompressed docs css'...
fs.js:89
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open '/Users/admin/Projects/docs/out/metadata.json'
```

**Comment by abolfazl-ziaratban** [comment]
i solved this problem.
semantic document is not clear.
## step by step
1. install [semantic-ui](https://semantic-ui.com/introduction/getting-started.html#installing) in this folder `c:\test\semantic-org`. (use default setting for installing)
    - **after install**
      - you can see folder `semantic` in `c:\test\semantic-org`
      - run `gulp build` in `c:\test\semantic-org\semantic`
        - after build , you can see folder `dist` in `c:\test\semantic-org\semantic`
3. **So far everything is good**
3. download [Semantic Docs](https://github.com/Semantic-Org/Semantic-UI-Docs) and extract to in `c:\test\docs`
    - **after install**
      - run `npm install -g docpad` in `c:\test\docs`
      - run `docpad install eco;` and `docpad update; docpad upgrade;` in `c:\test\docs`
      - run `docpad run` in `c:\test\docs`
        - after run
           - copy `c:\test\semantic-org\semantic\dist` to `c:\test\docs\out`
           - run  `gulp build-docs` in `c:\test\semantic-org\semantic`
4. go to http://localhost:9778
