### ISSUE TITLE
Gulp build error

### ISSUE THREAD

**Issue by apptouch** [Semantic-Org/Semantic-UI#5007]
Hi, I followed the issue around getting NPM upgraded to avoid the "gulp-help" module build error.  And, I got past that issue, but now I get the following:
```
c:\Work\Test\SemanticUI>cd semantic

c:\Work\Test\SemanticUI\semantic>gulp build
[12:46:43] Using gulpfile c:\Work\Test\SemanticUI\semantic\gulpfile.js
[12:46:43] Starting 'build'...
Building Semantic
[12:46:44] 'build' errored after 218 ms
[12:46:44] Error: Task build-javascript is not configured as a task on gulp.  If this is a submodule, you may need to use require('run-sequence').use(gulp).
    at c:\Work\Test\SemanticUI\node_modules\run-sequence\index.js:20:10
    at Array.forEach (native)
    at verifyTaskSets (c:\Work\Test\SemanticUI\node_modules\run-sequence\index.js:13:11)
    at c:\Work\Test\SemanticUI\node_modules\run-sequence\index.js:32:4
    at Array.forEach (native)
    at verifyTaskSets (c:\Work\Test\SemanticUI\node_modules\run-sequence\index.js:13:11)
    at runSequence (c:\Work\Test\SemanticUI\node_modules\run-sequence\index.js:92:2)
    at Gulp.module.exports (c:\Work\Test\SemanticUI\semantic\tasks\build.js:49:3)
    at module.exports (c:\Work\Test\SemanticUI\semantic\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (c:\Work\Test\SemanticUI\semantic\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
```

Have any ideas?  Thanks!

Chris

**Comment by vinayakkulkarni** [comment]
Check this comment by @IonutBajescu https://github.com/Semantic-Org/Semantic-UI/issues/4374#issuecomment-236729805

Also, there's [stackoverflow question](http://stackoverflow.com/questions/38962608/semantic-ui-error-while-importing-gulp-tasks) (with an answer) for this too.

Closing this for now. Use #4374 or [gitter](https://gitter.im/Semantic-Org/Semantic-UI) if you have any further doubts

**Comment by apptouch** [comment]
Thanks, that worked.
