### ISSUE TITLE
npm install fails on gulp install

### ISSUE THREAD

**Issue by rangelfinal** [Semantic-Org/Semantic-UI#5216]
npm install fails on gulp install with access denied.
My OS is in portuguese, "Acesso Negado" means "Access Denied".
Tried a complete node reinstall (Even deleted the .npm and .npm-cache folder), but to no avail.
npm even deletes the node_modules/semantic-ui folder after failing for some reason.

OS: Windows 10 Pro version 1607 build 14393.969
Node: 7.8.0
npm: 4.2.0
gulp: CLI version 3.9.1

```
C:\Users\vtr\Documents\Workspace\cati-next>npm install semantic-ui
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global js-beautify@1.5.10 should be installed with -g

> semantic-ui@2.2.10 install C:\Users\vtr\Documents\Workspace\cati-next\node_modules\semantic-ui
> gulp install

Acesso negado.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN cati-next@1.0.0 No description
npm WARN cati-next@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! semantic-ui@2.2.10 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.2.10 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vtr\AppData\Roaming\npm-cache\_logs\2017-03-30T14_27_53_925Z-debug.log
```

The revelant part of 2017-03-30T14_27_53_925Z-debug.log seems to be
```
53385 verbose If you need help, you may report this error at:
53385 verbose     <https://github.com/npm/npm/issues>
53386 warn cati-next@1.0.0 No repository field.
53387 verbose If you need help, you may report this error at:
53387 verbose     <https://github.com/npm/npm/issues>
53388 verbose stack Error: semantic-ui@2.2.10 install: `gulp install`
53388 verbose stack Exit status 1
53388 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
53388 verbose stack     at emitTwo (events.js:106:13)
53388 verbose stack     at EventEmitter.emit (events.js:194:7)
53388 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
53388 verbose stack     at emitTwo (events.js:106:13)
53388 verbose stack     at ChildProcess.emit (events.js:194:7)
53388 verbose stack     at maybeClose (internal/child_process.js:899:16)
53388 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
53389 verbose pkgid semantic-ui@2.2.10
53390 verbose cwd C:\Users\vtr\Documents\Workspace\cati-next
53391 error Windows_NT 10.0.14393
53392 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "semantic-ui"
53393 error node v7.8.0
53394 error npm  v4.2.0
53395 error code ELIFECYCLE
53396 error errno 1
53397 error semantic-ui@2.2.10 install: `gulp install`
53397 error Exit status 1
53398 error Failed at the semantic-ui@2.2.10 install script 'gulp install'.
```

**Comment by sstok** [comment]
Try using a shorter starting path then `C:\Users\vtr\Documents\Workspace\cati-next\node_modules\semantic-ui` Windows has a 256 character limit and npm tends to break this limit. `.node_modules/foobar-something/.node_modules/deeper/.node_modules` (you get the point...)

**Comment by rangelfinal** [comment]
It worked!
Thanks for the help.
