### ISSUE TITLE
Slider example page is not working

### ISSUE THREAD

**Issue by kovetskiy** [Semantic-Org/Semantic-UI#5295]
Hi, I've visited https://semantic-ui.com/modules/slider.html
and doesn't see what is slider, but I see javascript error in dev console:
```
jQuery.Deferred exception: $slider.slider is not a function TypeError: $slider.slider is not a function
    at HTMLDocument.semantic.dropdown.ready (https://semantic-ui.com/javascript/slider.js:19:6)
    at j (https://semantic-ui.com/javascript/library/jquery.min.js:2:29588)
    at k (https://semantic-ui.com/javascript/library/jquery.min.js:2:29902) undefined
```

Screenshot: 
![2017-04-21-16t10t45](https://cloud.githubusercontent.com/assets/8445924/25271104/2e52b512-26ad-11e7-927e-6fba31c6c7c0.png)

chrome://version:
```
Google Chrome	56.0.2924.87 (Official Build) (64-bit)
Revision	0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@{#895}
OS	Linux 
JavaScript	V8 5.6.326.50
Flash	25.0.0.148 /home/operator/.config/google-chrome/PepperFlash/25.0.0.148/libpepflashplayer.so
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Command Line	/opt/google/chrome/google-chrome --flag-switches-begin --enable-fast-unload --enable-tcp-fastopen --num-raster-threads=4 --flag-switches-end
```
OS: Arch Linux

Other doc pages works good.

**Comment by YamiOdymel** [comment]
The slider is an unfinished module.
