### ISSUE TITLE
npm install --save semantic-ui error under npm 5.0.3

### ISSUE THREAD

**Issue by u0hz** [Semantic-Org/Semantic-UI#5463]
npm install semantic-ui    =>  error
after try to install all dependencies:
npm install gulp-less        =>  error
after try to install all dependencies:
npm install accord            =>  error

here is the log file

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\u0hz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp-less@3.3.0' ]
2 info using npm@5.0.3
3 info using node@v6.10.3
4 verbose npm-session d591a8a0e4a6bd5b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/gulp-less 1895ms (from cache)
8 silly pacote version manifest for gulp-less@3.3.0 fetched in 1937ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule gulp-less@3.3.0 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/gulp-util 16ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/object-assign 16ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/less 18ms (from cache)
17 silly pacote range manifest for gulp-util@^3.0.7 fetched in 20ms
18 silly resolveWithNewModule gulp-util@3.0.8 checking installable status
19 silly pacote range manifest for object-assign@^4.0.1 fetched in 20ms
20 silly resolveWithNewModule object-assign@4.1.1 checking installable status
21 silly pacote range manifest for less@2.6.x || ^2.7.1 fetched in 23ms
22 silly resolveWithNewModule less@2.7.2 checking installable status
23 http fetch GET 304 https://registry.npmjs.org/accord 309ms (from cache)
24 silly fetchPackageMetaData error for accord@^0.26.3 Unexpected end of input at 1:25897
24 silly fetchPackageMetaData ies":{"LiveScript":"latest","acorn":"latest","babel":"latest","babel-
24 silly fetchPackageMetaData                                                                      ^
25 verbose stack SyntaxError: Unexpected end of input at 1:25897
25 verbose stack ies":{"LiveScript":"latest","acorn":"latest","babel":"latest","babel-
25 verbose stack                                                                      ^
25 verbose stack     at SyntaxError (native)
25 verbose stack     at Object.parseJSON (C:\Users\u0hz\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\node_modules\jju\lib\parse.js:745:13)
25 verbose stack     at parse (C:\Users\u0hz\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-helpfulerror\index.js:10:13)
25 verbose stack     at consumeBody.call.then.buffer (C:\Users\u0hz\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
25 verbose stack     at process._tickCallback (internal/process/next_tick.js:109:7)
26 verbose cwd D:\Workspace\cxvx\semantic
27 verbose Windows_NT 10.0.14393
28 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\u0hz\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-less@3.3.0"
29 verbose node v6.10.3
30 verbose npm  v5.0.3
31 error Unexpected end of input at 1:25897
31 error ies":{"LiveScript":"latest","acorn":"latest","babel":"latest","babel-
31 error                                                                      ^
32 verbose exit [ 1, true ]

**Comment by cueedee** [comment]
FYI, I experienced issues with `npm@5.0.3` (or `@5.0.4`) too but upgrading to `@5.3.0` fixed em.

**Comment by cueedee** [comment]
@stale-bot; Given the "needs milestone" status, I would presume that they still intend to address this issue at some point.
