### ISSUE TITLE
Cannot install if autoInstall true

### ISSUE THREAD

**Issue by italomaia** [Semantic-Org/Semantic-UI#5519]
If autoInstall is true, I'm getting the following error: 

```
npm install semantic-ui
> gulp install

module.js:487
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by italomaia** [comment]
How to reproduce:

```
npm install semantic-ui  # manually input all parameters
# now change autoInstall to true
rm -rf node_modules
npm install semantic  # here, we want to install only the dependencies
```

**Comment by italomaia** [comment]
Workaround:

yarn add semantic-ui --ignore-scripts
