### ISSUE TITLE
Nmp install semantic-ui --save is currently failing

### ISSUE THREAD

**Issue by johot** [Semantic-Org/Semantic-UI#5526]
Just tried install semantic ui via the npm package on two different computers and are getting the following error. Is the npm package broken? Thanks! This is happening on a Windows 7 and Windows 10 computer running git bash.

Console output:
```
npm install semantic-ui --save
npm WARN deprecated gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> semantic-ui@2.2.10 install E:\Repos\CurbitsWeb\node_modules\semantic-ui
> gulp install

[10:12:01] Using gulpfile E:\Repos\CurbitsWeb\node_modules\semantic-ui\gulpfile.js
[10:12:01] Starting 'install'...
[10:12:01] Starting 'run setup'...
? Set-up Semantic UI (Use arrow keys)
> Automatic (Use defaults locations and all components)
  Express (Set components and output folder)
  Custom (Customize all src/dist values) [10:12:01] 'run setup' errored after 19 ms
[10:12:01] SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at module.exports.ScreenManager.render (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (E:\Repos\CurbitsWeb\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (E:\Repos\CurbitsWeb\node_modules\rx-lite\rx.lite.js:63:31)
[10:12:01] 'install' errored after 21 ms
[10:12:01] SyntaxError in plugin 'run-sequence(run setup)'
Message:
    Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
Stack:
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at new RegExp (<anonymous>)
    at breakLines (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at module.exports.ScreenManager.render (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (E:\Repos\CurbitsWeb\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (E:\Repos\CurbitsWeb\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (E:\Repos\CurbitsWeb\node_modules\rx-lite\rx.lite.js:63:31)
```

**Comment by Banandrew** [comment]
Please see #5370 and #4292.

**Comment by johot** [comment]
Thank you! I fixed it by simply using PowerShell instead. Some mention it also works using the default windows commandline, so solve this by not using `git bash`. Thanks!

**Comment by atako** [comment]
I had same problem in Linux. I solved it using sh instead bash for exec 'npm install semantic-ui --save' command.
