### ISSUE TITLE
LESS Build failes

### ISSUE THREAD

**Issue by DerKnerd** [Semantic-Org/Semantic-UI#5909]
We are trying to use semantic UI in a project but when we call `gulp build` we get the following error message:

```
/home/vagrant/test/Semantic-UI/tasks/config/tasks.js:96
          if(error.filename.match(/theme.less/)) {
                           ^

TypeError: Cannot read property 'match' of undefined
    at DestroyableTransform.module.exports.settings.plumber.less.errorHandler (/
home/vagrant/test/Semantic-UI/tasks/config/tasks.js:96:28)
    at emitOne (events.js:82:20)
    at DestroyableTransform.emit (events.js:169:7)
    at onwriteError (/home/vagrant/test/Semantic-UI/node_modules/through2/node_m
odules/readable-stream/lib/_stream_writable.js:427:12)
    at onwrite (/home/vagrant/test/Semantic-UI/node_modules/through2/node_module
s/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/home/vagrant/test/Semantic-UI/node_modules/throug
h2/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/home/vagrant/test/Semantic-UI/node_modules/through2/node
_modules/readable-stream/lib/_stream_transform.js:104:3)
    at Immediate.TransformState.afterTransform (/home/vagrant/test/Semantic-UI/n
ode_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12
)
    at Immediate.immediate._onImmediate (timers.js:435:18)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The server is a vagrant [scotchbox](https://box.scotch.io/).

Can anyone help fixing this issue?

**Comment by matthew-p** [comment]
I'm getting the same error

**Comment by ridhozhr10** [comment]
just in case someone acounter this, maybe you are not installed less yet
# npm install -g less
thats it
