### ISSUE TITLE
Trouble installing with gulp

### ISSUE THREAD

**Issue by ryanmcgarvey** [Semantic-Org/Semantic-UI#6214]
### Trouble installing with gulp
I am able to install 2.2.13 with yarn and the  semantic.json bellow. However, version 2.3.14 and above give me the following error:

```bash
Updating Semantic UI from 2.2.13 to 2.3.0
Updating ui definitions...
[17:23:07] 'install' errored after 12 ms
[17:23:07] Error: ENOENT: no such file or directory, stat './src/definitions'
    at Object.fs.statSync (fs.js:968:11)
    at Object.exports.copyDirSyncRecursive (/Users/ryanmcgarvey/workspace/capitalpitch/node_modules/wrench-sui/lib/wrench.js:244:23)
    at Gulp.module.exports (/Users/ryanmcgarvey/workspace/capitalpitch/node_modules/semantic-ui/tasks/install.js:112:14)
    at module.exports (/Users/ryanmcgarvey/workspace/capitalpitch/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/ryanmcgarvey/workspace/capitalpitch/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/ryanmcgarvey/workspace/capitalpitch/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/ryanmcgarvey/workspace/capitalpitch/node_modules/orchestrator/index.js:134:8)
```

### semantic.json
```json
{
"base": "node_modules/semantic-ui/",
 "autoInstall": true,
 "paths": {
   "source": {
     "config": "src/theme.config",
     "definitions": "src/definitions/",
     "site": "src/site/",
     "themes": "src/themes/"
   },
   "output": {
     "packaged": "dist/",
     "uncompressed": "dist/components/",
     "compressed": "dist/components/",
     "themes": "dist/themes/"
   },
   "clean": "dist/"
 },
 "permission": false,
 "rtl": false
}
```

**Comment by hammy2899** [comment]
Take a look at this issue https://github.com/Semantic-Org/Semantic-UI/issues/4801
