### ISSUE TITLE
Update to 2.4.1 fails. TypeError: print is not a function

### ISSUE THREAD

**Issue by tyapkov** [Semantic-Org/Semantic-UI#6648]
I have the error **TypeError: print is not a function** while trying to build 2.4.1 with _gulp build_. At the same time 2.3.3 installs without any problems. What can be the reason?

> (node:29539) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
> [17:21:22] Using gulpfile ~/py/d/frontend/semantic/gulpfile.js
> [17:21:22] Starting 'build'...
> Building Semantic
> [17:21:22] Starting 'build-javascript'...
> Building Javascript
> [17:21:22] 'build-javascript' errored after 31 ms
> [17:21:22] TypeError: print is not a function
>     at Gulp.module.exports (/home/alexander/py/d/frontend/semantic/tasks/build/javascript.js:64:11)
>     at module.exports (/home/alexander/py/d/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:214:10)
>     at Gulp.Orchestrator.start (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:134:8)
>     at runNextSet (/home/alexander/py/d/frontend/node_modules/run-sequence/index.js:86:16)
>     at runSequence (/home/alexander/py/d/frontend/node_modules/run-sequence/index.js:97:2)
>     at Gulp.module.exports (/home/alexander/py/d/frontend/semantic/tasks/build.js:49:3)
>     at module.exports (/home/alexander/py/d/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:273:3)
> [17:21:22] 'build' errored after 35 ms
> [17:21:22] TypeError in plugin 'run-sequence(build-javascript)'
> Message:
>     print is not a function
> Stack:
> TypeError: print is not a function
>     at Gulp.module.exports (/home/alexander/py/d/frontend/semantic/tasks/build/javascript.js:64:11)
>     at module.exports (/home/alexander/py/d/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:214:10)
>     at Gulp.Orchestrator.start (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:134:8)
>     at runNextSet (/home/alexander/py/d/frontend/node_modules/run-sequence/index.js:86:16)
>     at runSequence (/home/alexander/py/d/frontend/node_modules/run-sequence/index.js:97:2)
>     at Gulp.module.exports (/home/alexander/py/d/frontend/semantic/tasks/build.js:49:3)
>     at module.exports (/home/alexander/py/d/frontend/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/home/alexander/py/d/frontend/node_modules/orchestrator/index.js:273:3)

**Comment by tyapkov** [comment]
I had older version of gulp-print. After `npm install gulp-print@5.0.0 --save-dev` the issue was solved.
