### ISSUE TITLE
gulp4 breaks build (after gulp was tagged latest today, from next)

### ISSUE THREAD

**Issue by mariusk** [Semantic-Org/Semantic-UI#6705]
Here's the relevant error (I think):
```
/Users/marius/p/wellplan/node_modules/gulp-help/index.js:81
    task = gulp.tasks[name];
                     ^

TypeError: Cannot read property 'help' of undefined
    at Gulp.gulp.task (/Users/marius/p/wellplan/node_modules/gulp-help/index.js:81:22)
    at module.exports (/Users/marius/p/wellplan/node_modules/gulp-help/index.js:97:8)
    at Object.<anonymous> (/Users/marius/p/wellplan/semantic/gulpfile.js:6:38)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by ColinFrick** [comment]
Gulp 4.x is not yet supported. Duplicate of #3793 

Ensure that you use the latest gulp 3.x

**Comment by mariusk** [comment]
I think there are dependencies of semantic-ui that now pulls in gulp 4, because it's now tagged as latest, and that breaks the build (gulp-help etc). At least that's what we're experiencing.

**Comment by ColinFrick** [comment]
How are you rebuilding semantic ui?
Executing `npx gulp build` in the semantic ui directory works for me.

```sh
mkdir semantic-ui-test && \
  cd semantic-ui-test && \
  npm init && \
  npm i semantic-ui && \
  cd semantic && \
  npx gulp build
```

**Comment by ColinFrick** [comment]
That happens if you don't select a value for "We detected you are using NPM Nice! Is this your project folder?"
No option is selected as a default

**Comment by mariusk** [comment]
Yeah, just noticed, sry.

**Comment by mariusk** [comment]
I noticed the latest version was 2.4.2, not 2.4.1 that I tested with. Upgraded to 2.4.2 and it worked as expected. Thanks!

**Comment by ArvindRSingh** [comment]
Please mention the node, npm, gulp cli/local version that Semantic Ui gets build. Preferably this should be mentioned in Readme file.
