### ISSUE TITLE
install fails with pnpm

### ISSUE THREAD

**Issue by cdfa** [Semantic-Org/Semantic-UI#6706]
✖ USAGE QUESTIONS → Use these dedicated resources:
      Docs - http://www.semantic-ui.com
      Chat - https://gitter.im/Semantic-Org/Semantic-UI
      SO - https://stackoverflow.com/questions/tagged/semantic-ui?sort=votes

✔ Enhancements → Be specific. Assume backwards compatibility is a necessity. Suggest implementation when possible.
✔ BUGS → ❤❤❤. Keep in mind some bugs may not be immediately fixable due to backwards compatibility or CSS limitations.

### Title (Put in field above)
Use the format: [Component] Component Should Do X
i.e. [Checkbox] onChange Should Fire When Update Triggered via DOM

### Description
I'm unable to install via [pnpm](https://pnpm.js.org/). It is 100% compliant with the npm module loading standard, but sometimes it breaks because packages do something outside of the standard. If you've looked into it and are confident this is a problem with pnpm, I'll report the issue there.

### Steps
- run `pnpm i semantic-ui`

### Expected Result
Command finishes without errors.

### Actual Result
```
Packages: +189
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 658, reused 658, downloaded 0, done
registry.npmjs.org/semantic-ui/2.4.2     |     install$ gulp install
registry.npmjs.org/semantic-ui/2.4.2     |     install:     at tryModuleLoad (module.js:506:12)
registry.npmjs.org/semantic-ui/2.4.2     |     install:     at Function.Module._load (module.js:
registry.npmjs.org/semantic-ui/2.4.2     |     install: Exited with 1
ERROR  semantic-ui@2.4.2 install: `gulp install`
Exit status 1
at Error: semantic-ui                                                                             at <anonymous>         /home/cdfa/.nvm/versions/node/v8.12.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/2.21.1/node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/index.js:301     var er = new Error('Exit…
at emitTwo             events.js:126                                                              at emit                events.js:214                                                              at <anonymous>         /home/cdfa/.nvm/versions/node/v8.12.0/pnpm-global/1/node_modules/.registry.npmjs.org/pnpm/2.21.1/node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/lib/spawn.js:55  cooked.emit('close', cod…
at emitTwo             events.js:126                                                              at emit                events.js:214                                                              at maybeClose          internal/child_process.js:915                                              at on                  internal/child_process.js:336                                              at emitOne             events.js:116                                                              at emit                events.js:211
```

### Version
2.4.2

### Testcase
[Fork, update, and replace to show the bug]:
https://jsfiddle.net/ca0rovs3/

**Comment by DanielRuf** [comment]
Try running `gulp install`.
What error does it show then?

**Comment by DanielRuf** [comment]
Try running `gulp install`.
Which error does it show then?

**Comment by cdfa** [comment]
After installing `gulp` globally, it shows:
```
[21:05:07] No gulpfile found
```
Then doing `npx -p touch nodetouch gulpfile.js` (from gulpjs.com) and trying again shows:
```
[21:13:12] Using gulpfile ~/Projects/static-sticky/gulpfile.js
[21:13:12] Task 'install' is not in your gulpfile
[21:13:12] Please check the documentation for proper gulpfile formatting`
```
I can't find anything about how to set up gulp in the readMe or the getting started page in the documentation.

**Comment by DanielRuf** [comment]
> npx -p touch nodetouch gulpfile.js

Looks kinda redundant. Why not just `touch gulpfile.js`?
That means that you have an empty gulpfile.

Is there not https://github.com/Semantic-Org/Semantic-UI/blob/master/gulpfile.js?

**Comment by DanielRuf** [comment]
So `pnpm i semantic-ui` does still not work?
Also it should be `npm install gulp-cli -g` which will then use either a global or local gulp version.

**Comment by DanielRuf** [comment]
> Try running `gulp install`.
> Which error does it show then?

This was meant for `node_modules/semantic-ui`.

**Comment by cdfa** [comment]
> This was meant for node_modules/semantic-ui.

Ah that makes a lot more sense.
So now I get this:
```
module.js:550
throw err;
^
Error: Cannot find module 'less'
at Function.Module._resolveFilename (module.js:548:15)
at Function.resolve (internal/module.js:18:19)
at resolve_engine_path (/home/cdfa/Projects/static-sticky/node_modules/.registry.npmjs.org/semantic-ui/2.4.2/node_modules/semantic-ui/node_modules/.registry.npmjs.org/accord/0.29.0/node_modules/accord/lib/index.js:65:18)
at Object.exports.load (/home/cdfa/Projects/static-sticky/node_modules/.registry.npmjs.org/semantic-ui/2.4.2/node_modules/semantic-ui/node_modules/.registry.npmjs.org/accord/0.29.0/node_modules/accord/lib/index.js:25:19)
at Object.<anonymous> (/home/cdfa/Projects/static-sticky/node_modules/.registry.npmjs.org/semantic-ui/2.4.2/node_modules/semantic-ui/node_modules/.registry.npmjs.org/gulp-less/4.0.1/node_modules/gulp-less/index.js:9:29)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
```

**Comment by cdfa** [comment]
Isn't this `accord`s problem then? Or at least not `semantic-ui`s? I could be wrong, I don't know anything about these packages.

**Comment by DanielRuf** [comment]
> Isn't this `accord`s problem then? Or at least not `semantic-ui`s? I could be wrong, I don't know anything about these packages.

Not directly accords issue as accord supports many dynamically defined adapters.
While Semantic UI uses the less adapter.

See https://github.com/jescalan/accord/tree/master/lib/adapters and https://github.com/jescalan/accord/blob/master/lib/index.coffee#L30-L43

**Comment by DanielRuf** [comment]
> While Semantic UI uses the less adapter.

Well, gulp-less does but it already defines `less` as direct dependency but `semantic-ui` does not which is the consumer and so pnpm can not directly link the dependency.

**Comment by DanielRuf** [comment]
https://github.com/gulp-community/gulp-less/blob/master/index.js#L9

If they would use a normal require, it would not be a problem and would work as pnpm can resolve it then, not like accord does only at runtime.

But fixing this in `gulp-less` takes longer and is not possible without any further tests and asking why they use `accord`.

**Comment by cdfa** [comment]
Ah, thanks for clarifying! I hope the PR gets merged soon.

**Comment by cdfa** [comment]
It seems adding less as dev dependency as suggested [here](https://github.com/pnpm/pnpm/issues/762) also works, which seems like a better solution to me. Thanks for helping anyway!
