### ISSUE TITLE
Invalid package name "Icon ": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters

### ISSUE THREAD

**Issue by nonodev96** [Semantic-Org/Semantic-UI#6816]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'semantic-ui',
1 verbose cli   '--save' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose config Skipping project config: /Users/nonodev96/.npmrc. (matches userconfig)
5 verbose npm-session ccfe29ade75abcf3
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/semantic-ui 35ms (from cache)
9 silly pacote tag manifest for semantic-ui@latest fetched in 62ms
10 verbose stack Error: Invalid package name "Icon
": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters
10 verbose stack     at invalidPackageName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:82:15)
10 verbose stack     at Result.setName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:118:11)
10 verbose stack     at new Result (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:107:23)
10 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:54:15)
10 verbose stack     at computeVersionSpec (/usr/local/lib/node_modules/npm/lib/install/deps.js:311:21)
10 verbose stack     at Installer.normalizeCurrentTree (/usr/local/lib/node_modules/npm/lib/install.js:404:68)
10 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
10 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
10 verbose stack     at iferr (/usr/local/lib/node_modules/npm/lib/install.js:362:5)
10 verbose stack     at a (/usr/local/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64)
10 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
10 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/call-limit/call-limit.js:22:12
10 verbose stack     at process._tickCallback (internal/process/next_tick.js:61:11)
11 verbose cwd /Users/nonodev96
12 verbose Darwin 18.6.0
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "semantic-ui" "--save"
14 verbose node v10.15.3
15 verbose npm  v6.9.0
16 error code EINVALIDPACKAGENAME
17 error Invalid package name "Icon
": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters
18 verbose exit [ 1, true ]

```

**Comment by nonodev96** [comment]
Solve: 😩

No update npm, only use npm@6.4.1

`npm install -g npm@6.4.1`

the version npm@6.9.0 not work with node@v10.15.3
