### ISSUE TITLE
Error: Cannot find module 'gulp-util' on gulp build

### ISSUE THREAD

**Issue by blainelawson** [Semantic-Org/Semantic-UI#6883]
During installation, `gulp-build` throws the following error:

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/nodejs/gulp/bin/gulp.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

I have attempted to remove and reinstall the node_modules directory, npm install gulp-util to no avail.

**Comment by ZweiDM** [comment]
In your project directory:
```
rm -rf node_modules

npm i -g npm@latest

npm i core-util-is
```
