### ISSUE TITLE
npm install semantic-ui not working

### ISSUE THREAD

**Issue by tluanga** [Semantic-Org/Semantic-UI#6920]
npm install semantic-ui
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> semantic-ui@2.4.2 install C:\dev\dawr_manager\dawr-front\node_modules\semantic-ui
> gulp install

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\dev\dawr_manager\dawr-front\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\dev\dawr_manager\dawr-front\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\dev\dawr_manager\dawr-front\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm WARN rollback Rolling back vinyl@1.2.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\dev\dawr_manager\dawr-front\node_modules\vinyl-file\node_modules'
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tluan\AppData\Roaming\npm-cache\_logs\2020-01-09T16_14_09_583Z-debug.log

**Comment by leoli-dev** [comment]
Same issue here, I can't find any help on the internet, sad.

- node: `v13.5.0`
- npm: `6.13.4`
- npx: `6.13.4`
- gulp: 

    ```
    CLI version: 2.2.0
    Local version: 4.0.2
    ```

---

Result:

```
> semantic-ui@2.4.2 install /Users/AJ/coding_projects/php/symfony5-test/node_modules/semantic-ui
> gulp install

fs.js:34
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:34:5
    at req_ (/Users/AJ/coding_projects/php/symfony5-test/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/AJ/coding_projects/php/symfony5-test/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/AJ/coding_projects/php/symfony5-test/node_modules/semantic-ui/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/AJ/.npm/_logs/2020-01-10T03_23_58_561Z-debug.log
```

---

At the end of this [closed ticket](https://github.com/Semantic-Org/Semantic-UI/issues/6705#issuecomment-446172432), someone said with `2.4.2` "it worked as expected", but it's not true.

**Comment by lubber-de** [comment]
Could you try if the community fork https://github.com/fomantic/Fomantic-UI works? It used Gulp 4 and supports newer node versions

**Comment by ArvindRSingh** [comment]
Which is the node, npm, gulp cli/local version Semantic UI works.

**Comment by ArvindRSingh** [comment]
Duplicate of #6897

**Comment by leoli-dev** [comment]
> Could you try if the community fork https://github.com/fomantic/Fomantic-UI works? It uses Gulp 4 and supports newer node versions

This library works, thank you.
