### ISSUE TITLE
Semantic UI Install - crash and fails to install

### ISSUE THREAD

**Issue by almacaw** [Semantic-Org/Semantic-UI#6921]
I have gone through the install instructions repeatedly but seem to be stuck with an error on installing Semantic locally. Any help would be much appreciated! Output is as below -
`al$ npm install semantic-ui --save`
`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> fsevents@1.2.11 install /Users/al/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> semantic-ui@2.4.2 install /Users/al/node_modules/semantic-ui
> gulp install

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/al/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/al/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/al/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
npm WARN enoent ENOENT: no such file or directory, open '/Users/al/package.json'
npm WARN al No description
npm WARN al No repository field.
npm WARN al No README data
npm WARN al No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/al/.npm/_logs/2020-01-19T16_12_13_183Z-debug.log`

**Comment by lubber-de** [comment]
Try the community fork https://github.com/fomantic/Fomantic-UI
. Supports gulp 4 and the mentioned dependency issue should also be fixed there
