### ISSUE TITLE
NPM not installing semantic-ui (gulp install)

### ISSUE THREAD

**Issue by danieltillero** [Semantic-Org/Semantic-UI#6934]
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> fsevents@1.2.11 install /Users/danieltillero/Desktop/NgBook/InventoryApp/node_modules/gulp-copy/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.11 install /Users/danieltillero/Desktop/NgBook/InventoryApp/node_modules/gulp-watch/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> semantic-ui@2.4.2 install /Users/danieltillero/Desktop/NgBook/InventoryApp/node_modules/semantic-ui
> gulp install

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/danieltillero/Desktop/NgBook/InventoryApp/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/danieltillero/Desktop/NgBook/InventoryApp/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/danieltillero/Desktop/NgBook/InventoryApp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm WARN karma-jasmine-html-reporter@1.5.1 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danieltillero/.npm/_logs/2020-02-05T15_08_47_724Z-debug.log
### Testcase
[Fork, update, and replace to show the bug]:
https://jsfiddle.net/ca0rovs3/

**Comment by lubber-de** [comment]
This was already reported several times unfortunately. The dependencies have not been updated since 2018. 
You may try the active community fork https://github.com/fomantic/Fomantic-UI which has up to date dependencies and uses gulp 4

**Comment by LeviBastosLima** [comment]
I tried to change my node version to 6.x and ran the ```npm install semantic-ui --save code again```, fortunately it ended up working.
