### ISSUE TITLE
Why is the semantic folder not created after installation?

### ISSUE THREAD

**Issue by 368573607** [Semantic-Org/Semantic-UI#6981]
the error say:

```npm
$ npm install semantic-ui --save
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> semantic-ui@2.4.2 install E:\semanticui
> gulp install

fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (E:\semanticui\node_modules\natives\index.js:143:24)
    at Object.req [as require] (E:\semanticui\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (E:\semanticui\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm WARN rollback Rolling back yargs@3.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'E:\semanticui\node_modules\uglify-js\node_modules'
npm WARN nodesy@1.0.0 No description
npm WARN nodesy@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the semantic-ui@2.4.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     E:\Program Files\nodejs\node_cache\_logs\2020-05-23T06_24_04_518Z-debug.log

```

![image](https://user-images.githubusercontent.com/60562136/82723660-01ddd780-9d03-11ea-8997-07deca8da5df.png)

please help Orz:fire:

**Comment by 368573607** [comment]
Ask for help from a great person Orz

**Comment by GammaGames** [comment]
Dependencies are out of date, see #6934 for more info. The community fork [fomantic/Fomantic-UI](https://github.com/fomantic/Fomantic-UI) is up to date.
