### ISSUE TITLE
[install ERROR] when installing semantic-ui

### ISSUE THREAD

**Issue by YongxinZz** [Semantic-Org/Semantic-UI#7035]
Cannot install semantic-ui on my macbook air. 
Can somebody help me with it?

adeMacBook-Air:UI_libary Joyce$ sudo npm install semantic-ui --save
Password:
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! code 1
npm ERR! path /Users/Joyce/Desktop/VisuAAL/UI_libary/node_modules/semantic-ui
npm ERR! command failed
npm ERR! command sh -c gulp install
npm ERR! fs.js:45
npm ERR! } = primordials;
npm ERR!     ^
npm ERR! 
npm ERR! ReferenceError: primordials is not defined
npm ERR!     at fs.js:45:5
npm ERR!     at req_ (/Users/Joyce/Desktop/VisuAAL/UI_libary/node_modules/natives/index.js:143:24)
npm ERR!     at Object.req [as require] (/Users/Joyce/Desktop/VisuAAL/UI_libary/node_modules/natives/index.js:55:10)
npm ERR!     at Object.<anonymous> (/Users/Joyce/Desktop/VisuAAL/UI_libary/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1102:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:967:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:807:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:991:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Joyce/.npm/_logs/2020-12-03T20_33_08_404Z-debug.log

**Comment by lubber-de** [comment]
You may try the community fork https://github.com/fomantic/Fomantic-UI
```
npm install fomantic-ui --save
```

**Comment by BarriowealthPro** [comment]
@lubber-de Any recommendations on migrating an existing project from semantic-ui to fomantic-ui?  Is it simply `npm remove semantic-ui` followed by `npm install fomantic-ui`? or do I still need to run `npx gulp build` in the /semantic directory?

**Comment by lubber-de** [comment]
> @lubber-de Any recommendations on migrating an existing project from semantic-ui to fomantic-ui?  Is it simply `npm remove semantic-ui` followed by `npm install fomantic-ui`? or do I still need to run `npx gulp build` in the /semantic directory?

Yes, it should be that simple.

**Comment by al-mutarjim** [comment]
`yarn add fomantic-ui --ignore-scripts` and then `yarn --cwd node_modules/fomantic-ui run install` took care of it in my case.
