### ISSUE TITLE
v2.5.0: Install reporting ERR_REQUIRE_ESM regarding del package and clean gulp script

### ISSUE THREAD

**Issue by mcrawshaw** [Semantic-Org/Semantic-UI#7094]
### Steps
Install the semantic-ui@2.5.0 package via npm or yarn.

### Actual Result
```
error /Users/markcrawshaw/Code/metamap/node_modules/semantic-ui: Command failed.
Exit code: 1
Command: gulp install
Arguments:
Directory: /Users/markcrawshaw/Code/metamap/node_modules/semantic-ui
Output:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/markcrawshaw/Code/metamap/node_modules/del/index.js from /Users/markcrawshaw/Code/metamap/node_modules/semantic-ui/tasks/clean.js not supported.
Instead change the require of index.js in /Users/markcrawshaw/Code/metamap/node_modules/semantic-ui/tasks/clean.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/markcrawshaw/Code/metamap/node_modules/semantic-ui/tasks/clean.js:8:12)
    at Object.<anonymous> (/Users/markcrawshaw/Code/metamap/node_modules/semantic-ui/gulpfile.js:21:18)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Version
2.5.0

### Recommendation
For users, you can force a resolution in your package.json to del@6.1. For maintainers, I suggest specifying 6.1 in the package.json (over *) or completing an overhaul of the gulp file to ESM (https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles/#transpilation).

**Comment by sepastian** [comment]
I had the same problem, thanks @mcrawshaw.

To get past this, I did:

```shell
git clone git@github.com:Semantic-Org/Semantic-UI.git
cd Semantic-UI
npm i --save-dev del@6.1
gulp install
```

**Comment by cameronroe** [comment]
I'm having the same issue. Why do we need to do a gulp install? I'm just looking for the lib here.

**Comment by mcrawshaw** [comment]
Not sure about @sepastian setup. Generally, you are just looking to force the resolution of the del package (general steps are different for yarn vs npm - check online).

**Comment by billchen2k** [comment]
Same issue here.

**Comment by sara-amani** [comment]
Same issue here.

**Comment by courtyenn** [comment]
I am still getting this.

**Comment by aorizondo** [comment]
same situation here
